apiVersion: v1
kind: Secret
metadata:
  name: fhir-env
type: Opaque
stringData:
  SAPASSWORD: {{ .Values.env.SAPASSWORD | quote }}
  ACCEPT_EULA: {{ .Values.env.ACCEPT_EULA  | quote }}
  FHIRServer__Security__Enabled: {{ .Values.env.FHIRServer__Security__Enabled | quote }}
  FHIRServer__Security__Authentication__Audience: {{ .Values.env.FHIRServer__Security__Authentication__Audience  | quote }}
  FHIRServer__Security__Authentication__Authority: {{ .Values.env.FHIRServer__Security__Authentication__Authority  | quote }}
  DataStore: {{ .Values.env.DataStore  | quote }}
  SqlServer__ConnectionString: {{ printf "Server=tcp:mssql-service,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connection Timeout=30;" .Values.env.SAPASSWORD  | quote }}
  SqlServer__AllowDatabaseCreation: {{ .Values.env.SqlServer__AllowDatabaseCreation  | quote }}
  SqlServer__Initialize: {{ .Values.env.SqlServer__Initialize  | quote }}
  ApplicationInsights__InstrumentationKey: {{ .Values.env.ApplicationInsights__InstrumentationKey  | quote }}
  ASPNETCORE_URLS: {{ printf "https://+:%s;http://+:%s" (.Values.fhir.httpsPort | toString)  (.Values.fhir.httpPort | toString)  | quote }}
  ASPNETCORE_Kestrel__Certificates__Default__Password: {{ .Values.fhir.certificatePassword  | quote }}
  ASPNETCORE_Kestrel__Certificates__Default__Path: {{ "/certs/mycertificatename.pfx"  | quote }}