kind: Namespace
apiVersion: v1
metadata:
  name: fhir-server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:  
  name: mssql-data
  namespace: fhir-server
spec:
  storageClassName: managed-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fhir-server
  name: fhir-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir-server
  template:
    metadata:
      labels:
        app: fhir-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fhir-api
        image: healthplatformregistry.azurecr.io/r4_fhir-server:latest
        ports:
        - containerPort: 8080
          name: fhir
        envFrom:
        - secretRef:
            name: fhir-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fhir-server
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql  
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:                   
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fhir-env
              key: SAPASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
kind: Service
apiVersion: v1
metadata:
  namespace: fhir-server
  name: fhir-service
spec:
  selector:
    app: fhir-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: fhir      
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  namespace: fhir-server
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: mssql
  type: LoadBalancer